In [1]:
import os

import torch
import torch.nn.functional as F

import numpy as np
import pandas as pd
import datetime
from datetime import datetime as dt

In [2]:
data_path = "./user01-06/user0"

usr_data = []
tmp = []

"""
usr_01_data = []
usr_02_data = []
usr_03_data = []
usr_04_data = []
usr_05_data = []
usr_06_data = []

usr_data -> 01~06
"""

for i in range(1, 7):
    data_path += str(i)
    dir_list = os.listdir(data_path)
    for item in dir_list:
        csv_file = data_path + "/" + item + "/" + item + "_label.csv"
        rdr = pd.read_csv(csv_file)
        tmp.append(rdr)
    data_path = data_path[:-1]
    usr_data.append(tmp)
    tmp = []

In [3]:
usr_01_data = usr_data[0]
usr_02_data = usr_data[1]
usr_03_data = usr_data[2]
usr_04_data = usr_data[3]
usr_05_data = usr_data[4]
usr_06_data = usr_data[5]

In [4]:
df_01 = pd.concat(usr_01_data, axis=0)
df_01['ts']=pd.to_datetime(df_01['ts'], unit='s')
df_01['is_weekend']=df_01.apply(lambda x: x['ts'].weekday()>=5, axis=1)
df_01['ampm']=df_01.apply(lambda x: ["AM","PM"][x['ts'].hour//12], axis=1)
df_01

,ts,action,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,emotionPositive,emotionTension,activity,is_weekend,ampm
0,2020-09-12 15:00:00,work,211,NaN,NaN,WITH_MANY,2.0,3.0,other_indoor,6,5,3,True,PM
1,2020-09-12 15:01:00,work,211,NaN,NaN,WITH_MANY,2.0,3.0,other_indoor,6,5,3,True,PM
2,2020-09-12 15:02:00,work,211,NaN,NaN,WITH_MANY,2.0,3.0,other_indoor,6,5,3,True,PM
3,2020-09-12 15:03:00,work,211,NaN,NaN,WITH_MANY,2.0,3.0,other_indoor,6,5,3,True,PM
4,2020-09-12 15:04:00,work,211,NaN,NaN,WITH_MANY,2.0,3.0,other_indoor,6,5,3,True,PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
618,2020-09-19 14:54:00,shop,91,NaN,NaN,ALONE,NaN,NaN,home,7,6,3,True,PM
619,2020-09-19 14:55:00,shop,91,NaN,NaN,ALONE,NaN,NaN,home,7,6,3,True,PM
620,2020-09-19 14:56:00,shop,91,NaN,NaN,ALONE,NaN,NaN,home,7,6,3,True,PM
621,2020-09-19 14:57:00,shop,91,NaN,NaN,ALONE,NaN,NaN,home,7,6,3,True,PM
622,2020-09-19 14:58:00,shop,91,NaN,NaN,ALONE,NaN,NaN,home,7,6,3,True,PM

In [5]:
df_02 = pd.concat(usr_02_data, axis=0)
df_02['ts']=pd.to_datetime(df_02['ts'], unit='s')
df_02['is_weekend']=df_02.apply(lambda x: x['ts'].weekday()>=5, axis=1)
df_02['ampm']=df_02.apply(lambda x: ["AM","PM"][x['ts'].hour//12], axis=1)
df_02

,ts,action,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,emotionPositive,emotionTension,activity,is_weekend,ampm
0,2020-09-26 15:00:00,socialising,711,NaN,NaN,WITH_ONE,2.0,3.0,other_indoor,5,3,3,True,PM
1,2020-09-26 15:01:00,socialising,711,NaN,NaN,WITH_ONE,2.0,3.0,other_indoor,5,3,3,True,PM
2,2020-09-26 15:02:00,socialising,711,NaN,NaN,WITH_ONE,2.0,3.0,other_indoor,5,3,3,True,PM
3,2020-09-26 15:03:00,socialising,711,NaN,NaN,WITH_ONE,2.0,3.0,other_indoor,5,3,3,True,PM
4,2020-09-26 15:04:00,socialising,711,NaN,NaN,WITH_ONE,2.0,3.0,other_indoor,5,3,3,True,PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967,2020-09-23 14:29:00,personal_care,132,NaN,NaN,ALONE,NaN,NaN,home,4,4,3,False,PM
968,2020-09-23 14:30:00,personal_care,132,NaN,NaN,ALONE,NaN,NaN,home,4,4,3,False,PM
969,2020-09-23 14:30:00,recreation_media,724,NaN,NaN,ALONE,NaN,NaN,home,4,4,3,False,PM
970,2020-09-23 14:31:00,recreation_media,724,NaN,NaN,ALONE,NaN,NaN,home,4,4,3,False,PM
971,2020-09-23 14:32:00,recreation_media,724,NaN,NaN,ALONE,NaN,NaN,home,4,4,3,False,PM

In [6]:
df_03 = pd.concat(usr_03_data, axis=0)
df_03['ts']=pd.to_datetime(df_03['ts'], unit='s')
df_03['is_weekend']=df_03.apply(lambda x: x['ts'].weekday()>=5, axis=1)
df_03['ampm']=df_03.apply(lambda x: ["AM","PM"][x['ts'].hour//12], axis=1)
df_03

,ts,action,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,emotionPositive,emotionTension,activity,is_weekend,ampm
0,2020-09-07 20:26:00,sleep,111,NaN,NaN,ALONE,NaN,NaN,home,5,2,3,False,PM
1,2020-09-07 20:53:00,sleep,111,NaN,NaN,ALONE,NaN,NaN,home,5,2,3,False,PM
2,2020-09-07 21:27:00,sleep,111,NaN,NaN,ALONE,NaN,NaN,home,5,2,3,False,PM
3,2020-09-07 21:52:00,sleep,111,NaN,NaN,ALONE,NaN,NaN,home,5,2,3,False,PM
4,2020-09-07 22:17:00,sleep,111,NaN,NaN,ALONE,NaN,NaN,home,5,2,3,False,PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,2020-09-09 09:24:00,entertainment,742,NaN,NaN,WITH_ONE,2.0,1.0,home,6,3,3,False,AM
655,2020-09-09 09:43:00,entertainment,742,NaN,NaN,WITH_ONE,2.0,1.0,home,6,3,3,False,AM
656,2020-09-09 10:10:00,entertainment,742,NaN,NaN,WITH_ONE,2.0,1.0,home,6,3,3,False,AM
657,2020-09-09 12:49:00,personal_care,132,NaN,NaN,WITH_ONE,2.0,2.0,home,6,1,4,False,PM
658,2020-09-09 13:51:00,recreation_media,722,NaN,NaN,WITH_ONE,2.0,2.0,home,6,1,4,False,PM

In [7]:
df_04 = pd.concat(usr_04_data, axis=0)
df_04['ts']=pd.to_datetime(df_04['ts'], unit='s')
df_04['is_weekend']=df_04.apply(lambda x: x['ts'].weekday()>=5, axis=1)
df_04['ampm']=df_04.apply(lambda x: ["AM","PM"][x['ts'].hour//12], axis=1)
df_04

,ts,action,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,emotionPositive,emotionTension,activity,is_weekend,ampm
0,2020-09-26 23:30:00,personal_care,132,NaN,NaN,ALONE,NaN,NaN,home,5,2,3,True,PM
1,2020-09-26 23:31:00,personal_care,132,NaN,NaN,ALONE,NaN,NaN,home,5,2,3,True,PM
2,2020-09-26 23:32:00,personal_care,132,NaN,NaN,ALONE,NaN,NaN,home,5,2,3,True,PM
3,2020-09-26 23:33:00,personal_care,132,NaN,NaN,ALONE,NaN,NaN,home,5,2,3,True,PM
4,2020-09-26 23:34:00,personal_care,132,NaN,NaN,ALONE,NaN,NaN,home,5,2,3,True,PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,2020-09-07 11:43:00,household,41,NaN,NaN,WITH_ONE,2.0,3.0,home,7,2,4,False,AM
774,2020-09-07 11:44:00,household,41,NaN,NaN,WITH_ONE,2.0,3.0,home,7,2,4,False,AM
775,2020-09-07 11:45:00,household,41,NaN,NaN,WITH_ONE,2.0,3.0,home,7,2,3,False,AM
776,2020-09-07 11:46:00,household,41,NaN,NaN,WITH_ONE,2.0,3.0,home,7,2,3,False,AM
777,2020-09-07 11:47:00,household,41,NaN,NaN,WITH_ONE,2.0,3.0,home,7,2,3,False,AM

In [8]:
df_05 = pd.concat(usr_05_data, axis=0)
df_05['ts']=pd.to_datetime(df_05['ts'], unit='s')
df_05['is_weekend']=df_05.apply(lambda x: x['ts'].weekday()>=5, axis=1)
df_05['ampm']=df_05.apply(lambda x: ["AM","PM"][x['ts'].hour//12], axis=1)
df_05

,ts,action,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,emotionPositive,emotionTension,activity,is_weekend,ampm
0,2020-09-03 23:49:00,recreation_media,723,NaN,NaN,WITH_ONE,1.0,1.0,home,5,4,4,False,PM
1,2020-09-03 23:50:00,recreation_media,723,NaN,NaN,WITH_ONE,1.0,1.0,home,5,4,3,False,PM
2,2020-09-03 23:51:00,recreation_media,723,NaN,NaN,WITH_ONE,1.0,1.0,home,5,4,3,False,PM
3,2020-09-03 23:52:00,recreation_media,723,NaN,NaN,WITH_ONE,1.0,1.0,home,5,4,3,False,PM
4,2020-09-03 23:53:00,recreation_media,723,NaN,NaN,WITH_ONE,1.0,1.0,home,5,4,3,False,PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,2020-09-02 12:01:00,recreation_media,722,NaN,NaN,WITH_ONE,1.0,1.0,home,4,2,3,False,PM
79,2020-09-02 12:02:00,recreation_media,722,NaN,NaN,WITH_ONE,1.0,1.0,home,4,2,3,False,PM
80,2020-09-02 12:05:00,recreation_media,722,NaN,NaN,WITH_ONE,1.0,1.0,home,4,2,3,False,PM
81,2020-09-02 12:26:00,recreation_media,722,NaN,NaN,WITH_ONE,1.0,1.0,home,4,2,3,False,PM
82,2020-09-02 12:29:00,recreation_media,722,NaN,NaN,WITH_ONE,1.0,1.0,home,4,2,3,False,PM

In [9]:
df_06 = pd.concat(usr_06_data, axis=0)
df_06['ts']=pd.to_datetime(df_06['ts'], unit='s')
df_06['is_weekend']=df_06.apply(lambda x: x['ts'].weekday()>=5, axis=1)
df_06['ampm']=df_06.apply(lambda x: ["AM","PM"][x['ts'].hour//12], axis=1)
df_06

,ts,action,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,emotionPositive,emotionTension,activity,is_weekend,ampm
0,2020-10-01 15:00:00,socialising,711,NaN,NaN,WITH_ONE,4.0,3.0,other_indoor,6,3,4,False,PM
1,2020-10-01 15:01:00,socialising,711,NaN,NaN,WITH_ONE,4.0,3.0,other_indoor,6,3,2,False,PM
2,2020-10-01 15:02:00,socialising,711,NaN,NaN,WITH_ONE,4.0,3.0,other_indoor,6,3,2,False,PM
3,2020-10-01 15:03:00,socialising,711,NaN,NaN,WITH_ONE,4.0,3.0,other_indoor,6,3,2,False,PM
4,2020-10-01 15:04:00,socialising,711,NaN,NaN,WITH_ONE,4.0,3.0,other_indoor,6,3,2,False,PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,2020-09-29 14:54:00,recreation_media,725,NaN,NaN,ALONE,NaN,NaN,home,3,3,3,False,PM
960,2020-09-29 14:55:00,recreation_media,725,NaN,NaN,ALONE,NaN,NaN,home,3,3,3,False,PM
961,2020-09-29 14:56:00,recreation_media,725,NaN,NaN,ALONE,NaN,NaN,home,3,3,3,False,PM
962,2020-09-29 14:57:00,recreation_media,725,NaN,NaN,ALONE,NaN,NaN,home,3,3,3,False,PM
963,2020-09-29 14:58:00,recreation_media,725,NaN,NaN,ALONE,NaN,NaN,home,3,3,3,False,PM

In [10]:
type_actions = []

In [11]:
action_count = []

In [12]:
type_actionOptions = []

In [13]:
actionOption_count = []

In [14]:
type_conditions = []

In [15]:
condition_count = []

In [16]:
type_activity = []

In [17]:
actionOption_dict = {'111': 'Sleep', '112': 'Sleepless', '121': 'Meal', '122': 'Snack', '131': 'Medical services, treatments, sick rest', '132': 'Personal hygiene (bath)', '133': 'Appearance management (makeup, change of clothes)', '134': 'Beauty-related services', '211': 'Main job', '212': 'Side job', '213': 'Rest during work', '22': 'Job search', '311': 'School class / seminar (listening)', '312': 'Break between classes', '313': 'School homework, self-study (individual)', '314': 'Team project (in groups)', '321': 'Private tutoring (offline)', '322': 'Online courses', '41': 'Preparing food and washing dishes', '42': 'Laundry and ironing', '43': 'Housing management and cleaning', '44': 'Vehicle management', '45': 'Pet and plant caring', '46': 'Purchasing goods and services (grocery/take-out)', '51': 'Caring for children under 10 who live together', '52': 'Caring for elementary, middle, and high school students over 10 who live together', '53': 'Caring for a spouse', '54': 'Caring for parents and grandparents who live together', '55': 'Caring for other family members who live together', '56': 'Caring for parents and grandparents who do not live together', '57': 'Caring for other family members who do not live together', '81': 'Personal care-related travel', '82': 'Commuting and work-related travel', '83': 'Education-related travel', '84': 'Travel related to housing management', '85': 'Travel related to caring for family and household members', '86': 'Travel related to participation and volunteering', '87': 'Socializing and leisure-related travel', '61': 'Religious activities', '62': 'Political activity', '63': 'Ceremonial activities', '64': 'Volunteer', '711': 'Offline communication', '712': 'Video or voice call', '713': 'Text or email (Online)', '721': 'Reading books, newspapers, and magazines', '722': 'Watching TV or video', '723': 'Listening to audio', '724': 'Internet search or blogging', '725': 'Gaming (mobile, computer, video)', '741': 'Watching a sporting event', '742': 'Watching movie', '743': 'Concerts and plays', '744': 'Amusement Park, zoo', '745': 'Festival, carnival', '746': 'Driving, sightseeing, excursion', '751': 'Walking', '752': 'Running, jogging', '753': 'Climbing, hiking', '754': 'Biking', '755': 'Ball games (soccer, basketball, baseball, tennis, etc)', '756': 'Camping, fishing', '761': 'Group games (board games, card games, puzzles, etc.)', '762': 'Personal hobbies (woodworking, gardening, etc.)', '763': 'Group performances (orchestra, choir, troupe, etc.)', '764': 'Liberal arts and learning (languages, musical instruments, etc.)', '791': 'Nightlife', '792': 'Smoking', '793': 'Do nothing and rest', '91': 'Online shopping', '92': 'Offline shopping'}
actionOption_dict

{'111': 'Sleep',
 '112': 'Sleepless',
 '121': 'Meal',
 '122': 'Snack',
 '131': 'Medical services, treatments, sick rest',
 '132': 'Personal hygiene (bath)',
 '133': 'Appearance management (makeup, change of clothes)',
 '134': 'Beauty-related services',
 '211': 'Main job',
 '212': 'Side job',
 '213': 'Rest during work',
 '22': 'Job search',
 '311': 'School class / seminar (listening)',
 '312': 'Break between classes',
 '313': 'School homework, self-study (individual)',
 '314': 'Team project (in groups)',
 '321': 'Private tutoring (offline)',
 '322': 'Online courses',
 '41': 'Preparing food and washing dishes',
 '42': 'Laundry and ironing',
 '43': 'Housing management and cleaning',
 '44': 'Vehicle management',
 '45': 'Pet and plant caring',
 '46': 'Purchasing goods and services (grocery/take-out)',
 '51': 'Caring for children under 10 who live together',
 '52': 'Caring for elementary, middle, and high school students over 10 who live together',
 '53': 'Caring for a spouse',
 '54': 'Caring for parents and grandparents who live together',
 '55': 'Caring for other family members who live together',
 '56': 'Caring for parents and grandparents who do not live together',
 '57': 'Caring for other family members who do not live together',
 '81': 'Personal care-related travel',
 '82': 'Commuting and work-related travel',
 '83': 'Education-related travel',
 '84': 'Travel related to housing management',
 '85': 'Travel related to caring for family and household members',
 '86': 'Travel related to participation and volunteering',
 '87': 'Socializing and leisure-related travel',
 '61': 'Religious activities',
 '62': 'Political activity',
 '63': 'Ceremonial activities',
 '64': 'Volunteer',
 '711': 'Offline communication',
 '712': 'Video or voice call',
 '713': 'Text or email (Online)',
 '721': 'Reading books, newspapers, and magazines',
 '722': 'Watching TV or video',
 '723': 'Listening to audio',
 '724': 'Internet search or blogging',
 '725': 'Gaming (mobile, computer, video)',
 '741': 'Watching a sporting event',
 '742': 'Watching movie',
 '743': 'Concerts and plays',
 '744': 'Amusement Park, zoo',
 '745': 'Festival, carnival',
 '746': 'Driving, sightseeing, excursion',
 '751': 'Walking',
 '752': 'Running, jogging',
 '753': 'Climbing, hiking',
 '754': 'Biking',
 '755': 'Ball games (soccer, basketball, baseball, tennis, etc)',
 '756': 'Camping, fishing',
 '761': 'Group games (board games, card games, puzzles, etc.)',
 '762': 'Personal hobbies (woodworking, gardening, etc.)',
 '763': 'Group performances (orchestra, choir, troupe, etc.)',
 '764': 'Liberal arts and learning (languages, musical instruments, etc.)',
 '791': 'Nightlife',
 '792': 'Smoking',
 '793': 'Do nothing and rest',
 '91': 'Online shopping',
 '92': 'Offline shopping'}

In [18]:
def feature_engineering(df):
    type_actions = list(df['action'].drop_duplicates())
    action_count = df['action'].value_counts()
    type_actionOptions = list(df['actionOption'].drop_duplicates())
    actionOption_count = df['actionOption'].value_counts()
    type_conditions = list(df['condition'].drop_duplicates())
    condition_count = df['condition'].value_counts()
    type_activity = list(df['activity'].drop_duplicates())
    return type_actions, action_count, type_actionOptions, actionOption_count, type_conditions, condition_count, type_activity

In [19]:
# dataframe을 tensor로 변환하는 method
def dfToTensor(df, list_attributes):
    attribute_tensors = []
    for attribute in list_attributes:
        type_attributes = list(df[attribute].drop_duplicates())
        tensor = torch.Tensor([x for x in df.apply(lambda x: type_attributes.index(x[attribute]), axis=1)]).to(torch.int64)
        attribute_tensors.append(tensor)
    return attribute_tensors

In [20]:
def indexToOneHot(attribute_tensors):
    return([F.one_hot(x) for x in attribute_tensors])

In [21]:
def data_distribution(df):
    for action in type_actions:
        print("{}: {:.3f}%".format(action, 100*action_count[action]/sum(list(action_count))))
        for actionOption in list(df['actionOption'][df['action']==action].drop_duplicates()):
            print("       ㄴ{}: {:.3f}%".format(actionOption_dict[str(actionOption)], 100*actionOption_count[actionOption]/sum(list(action_count))))

In [22]:
type_actions, action_count, type_actionOptions, actionOption_count, type_conditions, condition_count, type_activity = feature_engineering(df_01)
indexToOneHot(dfToTensor(df_01, ['action', 'place']))
data_distribution(df_01)

work: 16.653%
       ㄴMain job: 11.795%
       ㄴRest during work: 3.570%
       ㄴSide job: 1.288%
travel: 23.813%
       ㄴPersonal care-related travel: 12.505%
       ㄴCommuting and work-related travel: 9.787%
       ㄴTravel related to housing management: 0.304%
       ㄴSocializing and leisure-related travel: 0.304%
       ㄴTravel related to participation and volunteering: 0.507%
       ㄴTravel related to caring for family and household members: 0.406%
household: 4.746%
       ㄴLaundry and ironing: 0.010%
       ㄴHousing management and cleaning: 4.320%
       ㄴPreparing food and washing dishes: 0.416%
recreation_media: 18.783%
       ㄴWatching TV or video: 6.481%
       ㄴGaming (mobile, computer, video): 6.582%
       ㄴInternet search or blogging: 3.519%
       ㄴListening to audio: 1.643%
       ㄴReading books, newspapers, and magazines: 0.558%
personal_care: 4.919%
       ㄴMedical services, treatments, sick rest: 1.876%
       ㄴAppearance management (makeup, change of clothes): 1.126%
       ㄴPersonal hygiene (bath): 1.917%
meal: 13.682%
       ㄴMeal: 11.187%
       ㄴSnack: 2.495%
socialising: 0.963%
       ㄴOffline communication: 0.811%
       ㄴText or email (Online): 0.152%
recreation_etc: 4.087%
       ㄴDo nothing and rest: 4.087%
shop: 1.531%
       ㄴOnline shopping: 1.369%
       ㄴOffline shopping: 0.162%
study: 3.844%
       ㄴOnline courses: 0.710%
       ㄴSchool class / seminar (listening): 0.365%
       ㄴSchool homework, self-study (individual): 1.481%
       ㄴTeam project (in groups): 1.288%
hobby: 4.300%
       ㄴPersonal hobbies (woodworking, gardening, etc.): 3.134%
       ㄴLiberal arts and learning (languages, musical instruments, etc.): 0.304%
       ㄴGroup performances (orchestra, choir, troupe, etc.): 0.862%
sleep: 1.684%
       ㄴSleepless: 0.659%
       ㄴSleep: 1.024%
outdoor_act: 0.588%
       ㄴCamping, fishing: 0.203%
       ㄴWalking: 0.385%
entertainment: 0.051%
       ㄴConcerts and plays: 0.051%
community_interaction: 0.355%
       ㄴReligious activities: 0.355%

In [23]:
type_actions, action_count, type_actionOptions, actionOption_count, type_conditions, condition_count, type_activity = feature_engineering(df_02)
indexToOneHot(dfToTensor(df_02, ['action', 'place']))
data_distribution(df_02)

socialising: 4.712%
       ㄴOffline communication: 4.048%
       ㄴText or email (Online): 0.664%
travel: 5.774%
       ㄴPersonal care-related travel: 1.711%
       ㄴCommuting and work-related travel: 4.063%
personal_care: 6.725%
       ㄴPersonal hygiene (bath): 3.783%
       ㄴBeauty-related services: 1.549%
       ㄴAppearance management (makeup, change of clothes): 1.394%
sleep: 26.598%
       ㄴSleep: 26.598%
recreation_media: 8.539%
       ㄴWatching TV or video: 7.750%
       ㄴInternet search or blogging: 0.391%
       ㄴGaming (mobile, computer, video): 0.184%
       ㄴListening to audio: 0.214%
household: 0.996%
       ㄴPreparing food and washing dishes: 0.811%
       ㄴPurchasing goods and services (grocery/take-out): 0.184%
meal: 9.638%
       ㄴMeal: 9.195%
       ㄴSnack: 0.442%
study: 2.692%
       ㄴSchool homework, self-study (individual): 2.692%
work: 33.641%
       ㄴMain job: 32.630%
       ㄴSide job: 0.922%
       ㄴRest during work: 0.088%
recreation_etc: 0.686%
       ㄴDo nothing and rest: 0.686%

In [24]:
type_actions, action_count, type_actionOptions, actionOption_count, type_conditions, condition_count, type_activity = feature_engineering(df_03)
indexToOneHot(dfToTensor(df_03, ['action', 'place']))
data_distribution(df_03)

sleep: 21.425%
       ㄴSleep: 18.771%
       ㄴSleepless: 2.654%
personal_care: 3.658%
       ㄴPersonal hygiene (bath): 1.981%
       ㄴAppearance management (makeup, change of clothes): 1.678%
recreation_etc: 10.317%
       ㄴDo nothing and rest: 4.104%
       ㄴNightlife: 6.213%
work: 18.425%
       ㄴMain job: 16.363%
       ㄴRest during work: 1.943%
       ㄴSide job: 0.118%
household: 6.506%
       ㄴHousing management and cleaning: 3.014%
       ㄴPreparing food and washing dishes: 2.384%
       ㄴLaundry and ironing: 0.379%
       ㄴPurchasing goods and services (grocery/take-out): 0.730%
recreation_media: 20.647%
       ㄴInternet search or blogging: 4.905%
       ㄴWatching TV or video: 14.430%
       ㄴReading books, newspapers, and magazines: 1.076%
       ㄴListening to audio: 0.237%
meal: 6.796%
       ㄴMeal: 6.298%
       ㄴSnack: 0.498%
shop: 0.218%
       ㄴOnline shopping: 0.218%
socialising: 3.094%
       ㄴVideo or voice call: 0.848%
       ㄴText or email (Online): 0.763%
       ㄴOffline communication: 1.483%
travel: 5.398%
       ㄴCommuting and work-related travel: 2.327%
       ㄴPersonal care-related travel: 0.355%
       ㄴSocializing and leisure-related travel: 1.730%
       ㄴTravel related to housing management: 0.322%
       ㄴTravel related to caring for family and household members: 0.663%
outdoor_act: 3.222%
       ㄴCamping, fishing: 2.393%
       ㄴWalking: 0.284%
       ㄴBiking: 0.545%
hobby: 0.280%
       ㄴLiberal arts and learning (languages, musical instruments, etc.): 0.280%
entertainment: 0.014%
       ㄴWatching movie: 0.014%

In [25]:
type_actions, action_count, type_actionOptions, actionOption_count, type_conditions, condition_count, type_activity = feature_engineering(df_04)
indexToOneHot(dfToTensor(df_04, ['action', 'place']))
data_distribution(df_04)

personal_care: 3.178%
       ㄴPersonal hygiene (bath): 1.899%
       ㄴAppearance management (makeup, change of clothes): 1.279%
meal: 9.064%
       ㄴMeal: 8.327%
       ㄴSnack: 0.737%
recreation_media: 5.452%
       ㄴInternet search or blogging: 3.382%
       ㄴGaming (mobile, computer, video): 2.007%
       ㄴWatching TV or video: 0.063%
travel: 13.671%
       ㄴPersonal care-related travel: 0.606%
       ㄴSocializing and leisure-related travel: 4.661%
       ㄴCommuting and work-related travel: 8.183%
       ㄴTravel related to housing management: 0.222%
socialising: 8.915%
       ㄴOffline communication: 2.717%
       ㄴVideo or voice call: 6.198%
work: 43.544%
       ㄴSide job: 3.883%
       ㄴMain job: 38.504%
       ㄴRest during work: 1.157%
household: 5.931%
       ㄴPurchasing goods and services (grocery/take-out): 0.542%
       ㄴPreparing food and washing dishes: 4.281%
       ㄴHousing management and cleaning: 0.927%
       ㄴLaundry and ironing: 0.181%
outdoor_act: 6.854%
       ㄴWalking: 1.555%
       ㄴRunning, jogging: 1.130%
       ㄴCamping, fishing: 4.168%
recreation_etc: 2.993%
       ㄴDo nothing and rest: 2.993%
shop: 0.181%
       ㄴOffline shopping: 0.181%
hobby: 0.217%
       ㄴPersonal hobbies (woodworking, gardening, etc.): 0.217%

In [26]:
type_actions, action_count, type_actionOptions, actionOption_count, type_conditions, condition_count, type_activity = feature_engineering(df_05)
indexToOneHot(dfToTensor(df_05, ['action', 'place']))
data_distribution(df_05)

recreation_media: 22.673%
       ㄴListening to audio: 2.242%
       ㄴGaming (mobile, computer, video): 3.821%
       ㄴWatching TV or video: 15.462%
       ㄴReading books, newspapers, and magazines: 0.197%
       ㄴInternet search or blogging: 0.951%
travel: 10.188%
       ㄴCommuting and work-related travel: 5.202%
       ㄴTravel related to housing management: 1.274%
       ㄴPersonal care-related travel: 0.753%
       ㄴTravel related to caring for family and household members: 2.511%
       ㄴSocializing and leisure-related travel: 0.448%
work: 27.534%
       ㄴMain job: 27.139%
       ㄴRest during work: 0.395%
meal: 11.910%
       ㄴMeal: 11.139%
       ㄴSnack: 0.771%
recreation_etc: 4.305%
       ㄴDo nothing and rest: 4.251%
       ㄴNightlife: 0.054%
personal_care: 12.682%
       ㄴPersonal hygiene (bath): 8.430%
       ㄴAppearance management (makeup, change of clothes): 4.251%
shop: 0.108%
       ㄴOffline shopping: 0.108%
sleep: 1.022%
       ㄴSleep: 1.022%
household: 4.610%
       ㄴPreparing food and washing dishes: 2.188%
       ㄴHousing management and cleaning: 1.202%
       ㄴPurchasing goods and services (grocery/take-out): 1.220%
care_housemem: 3.462%
       ㄴCaring for parents and grandparents who do not live together: 3.283%
       ㄴCaring for a spouse: 0.179%
socialising: 1.507%
       ㄴVideo or voice call: 0.179%
       ㄴOffline communication: 1.327%

In [27]:
type_actions, action_count, type_actionOptions, actionOption_count, type_conditions, condition_count, type_activity = feature_engineering(df_06)
indexToOneHot(dfToTensor(df_06, ['action', 'place']))
data_distribution(df_06)

socialising: 4.285%
       ㄴOffline communication: 3.514%
       ㄴVideo or voice call: 0.472%
       ㄴText or email (Online): 0.299%
recreation_media: 42.850%
       ㄴWatching TV or video: 11.956%
       ㄴGaming (mobile, computer, video): 21.201%
       ㄴInternet search or blogging: 8.184%
       ㄴReading books, newspapers, and magazines: 1.509%
sleep: 6.634%
       ㄴSleep: 6.634%
meal: 4.809%
       ㄴMeal: 4.485%
       ㄴSnack: 0.324%
personal_care: 3.756%
       ㄴAppearance management (makeup, change of clothes): 2.333%
       ㄴPersonal hygiene (bath): 1.423%
travel: 8.007%
       ㄴCommuting and work-related travel: 5.031%
       ㄴPersonal care-related travel: 0.066%
       ㄴSocializing and leisure-related travel: 0.923%
       ㄴTravel related to housing management: 0.873%
       ㄴTravel related to participation and volunteering: 1.115%
work: 26.745%
       ㄴMain job: 18.807%
       ㄴRest during work: 3.879%
       ㄴSide job: 4.059%
household: 0.976%
       ㄴPurchasing goods and services (grocery/take-out): 0.361%
       ㄴHousing management and cleaning: 0.529%
       ㄴLaundry and ironing: 0.086%
outdoor_act: 0.234%
       ㄴRunning, jogging: 0.234%
shop: 0.664%
       ㄴOffline shopping: 0.504%
       ㄴOnline shopping: 0.160%
recreation_etc: 0.685%
       ㄴDo nothing and rest: 0.685%
community_interaction: 0.357%
       ㄴCeremonial activities: 0.357%